name: NullForge
main: com.github.nullforge.NullForge
version: '${project.version}'
depend: [NullCore, ProtocolLib, MythicMobs]
commands:
  dz:
    description: none.
    usage: /<command> ?
  hc:
    description: none.
    usage: /<command> ?
  baoshi:
    description: 客户定制功能
    usage: /<command> ?
  fadmin:
    description: none.
    usage: /<command> ?
    permission: nullforge.admin
permissions:
  nullforge.admin:
    description: Allows access to all admin commands
    default: op